# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: voicheer
#   annotations:
#     iam.gke.io/gcp-service-account: api-voicheer@api-voicheer.iam.gserviceaccount.com

# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandbox
  labels:
    app: sandbox

spec:
  replicas: 3
  selector:
    matchLabels:
      app: sandbox
  template:
    metadata:
      labels:
        app: sandbox
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
