apiVersion: v1
kind: ServiceAccount
metadata:
  name: sandbox
  annotations:
    iam.gke.io/gcp-service-account: dev-sandbox@gke-autopilot-blog.iam.gserviceaccount.com

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandbox

spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sandbox
    spec:
      serviceAccountName: dev-sandbox
